/*
    File: modules/runtime.pwn
    Purpose: Preserves dependency-safe compile order for cross-module runtime logic, dialogs, and commands while domain loaders stay clean.
    Notes: Keep this bridge limited to ordered includes. Move files out only when their compile dependencies are owned by a safer module loader.
*/

// ====== Refactored Functions moved to Modular Logic files ======
#include "modules/core/utils.pwn"
#include "modules/player/logic/connection.pwn"
#include "modules/system/logic/inventory.pwn"
#include "modules/property/logic/storage.pwn"
#include "modules/vehicle/logic/storage.pwn"
#include "modules/vehicle/logic/businesscleanup.pwn"
#include "modules/player/logic/runtime.pwn"
#include "modules/system/logic/reports.pwn"
#include "modules/interface/dialogs/styles.pwn"
#include "modules/interface/logic/playertextdraws.pwn"
#include "modules/core/logic/flymode.pwn"

#include "modules/player/logic/session.pwn"
#include "modules/core/logic/validation.pwn"
#include "modules/vehicle/logic/names.pwn"
#include "modules/vehicle/logic/traits.pwn"
#include "modules/core/database/queries.pwn"
#include "modules/core/database/callbacks.pwn"
#include "modules/interface/logic/flashing.pwn"
#include "modules/core/logic/timers.pwn"
#include "modules/vehicle/logic/events.pwn"
#include "modules/player/logic/events.pwn"
#include "modules/economy/logic/server.pwn"

#include "modules/core/logic/initialization.pwn"
#include "modules/interface/logic/selection.pwn"
#include "modules/interface/logic/clicks.pwn"

// ====== Refactored Dialogs moved to Modular files ======
#include "modules/interface/dialogs/base.pwn"
#include "modules/dynamic/dialogs/billboards.pwn"
#include "modules/system/dialogs/graffiti.pwn"
#include "modules/system/dialogs/radio.pwn"
#include "modules/player/dialogs/tasks.pwn"
#include "modules/system/dialogs/pickups.pwn"
#include "modules/job/dialogs/delivery.pwn"
#include "modules/faction/dialogs/ranks.pwn"
#include "modules/job/dialogs/taxi.pwn"
#include "modules/job/dialogs/shipments.pwn"
#include "modules/system/dialogs/racks.pwn"
#include "modules/core/dialogs/admin.pwn"
#include "modules/vehicle/dialogs/tuning.pwn"
#include "modules/property/dialogs/entrances.pwn"
#include "modules/vehicle/dialogs/impound.pwn"
#include "modules/system/dialogs/items.pwn"
#include "modules/system/dialogs/backpacks.pwn"
#include "modules/player/dialogs/tutorial.pwn"
#include "modules/player/dialogs/tickets.pwn"
#include "modules/mapping/dialogs/navigation.pwn"
#include "modules/faction/dialogs/enforcement.pwn"
#include "modules/faction/dialogs/locker.pwn"
#include "modules/job/dialogs/jobs.pwn"
#include "modules/system/dialogs/crates.pwn"
#include "modules/vehicle/dialogs/creation.pwn"
#include "modules/system/dialogs/phone.pwn"
#include "modules/furniture/dialogs/catalog.pwn"
#include "modules/vehicle/dialogs/dealership.pwn"
#include "modules/economy/dialogs/banking.pwn"
#include "modules/player/dialogs/teleport.pwn"
#include "modules/job/dialogs/drivingschool.pwn"
#include "modules/system/dialogs/inventory.pwn"
#include "modules/property/dialogs/business.pwn"
#include "modules/vehicle/dialogs/storage.pwn"
#include "modules/property/dialogs/storage.pwn"
#include "modules/player/dialogs/accessories.pwn"
#include "modules/player/dialogs/characters.pwn"
#include "modules/player/dialogs/account.pwn"

// ====== Refactored Command Handlers moved to Modular Command files ======
#include "modules/core/commands/administration.pwn"
#include "modules/faction/commands/faction.pwn"
#include "modules/player/commands/player.pwn"
#include "modules/vehicle/commands/vehicle.pwn"
#include "modules/system/commands/system.pwn"
#include "modules/property/commands/property.pwn"
#include "modules/job/commands/job.pwn"
#include "modules/economy/commands/economy.pwn"
#include "modules/dynamic/commands/billboard.pwn"
#include "modules/furniture/commands/furniture.pwn"
#include "modules/interface/commands/interface.pwn"
